wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,6 +52,11 @@ jobs:
         shell: bash
         run: nimble test
 
+      - name: Package dir state on failure
+        #if: failure()
+        shell: bash
+        run: ls -la ~/.nimble/pkgs2 ~/.nimble/nimbinaries nimbledeps/pkgs2 || true
+
   lint:
     name: Lint
     runs-on: ubuntu-latest
